BrainfinityWebApp/Controllers/TakmicenjeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using BrainfinityWebApp.Models;
using Microsoft.AspNetCore.Mvc;
using SmartBreadcrumbs.Attributes;
using BrainfinityWebApp.ViewModels;
using System.Globalization;
using System.Net.Http.Headers;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Newtonsoft.Json;
using System.IdentityModel.Tokens.Jwt;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;
using System.Collections;

namespace BrainfinityWebApp.Controllers
{
    [Authorize(Roles = "Supervizor")]
    public class TakmicenjeController : Controller
    {
        private readonly IHttpClientFactory _clientFactory;
        private readonly IHostingEnvironment _environment;

        public TakmicenjeController(IHttpClientFactory client, IHostingEnvironment environment)
        {
            _clientFactory = client;
            _environment = environment;
        }

        [Breadcrumb("Takmičenja", FromAction = ("Index"), FromController = typeof(HomeController))]
        public async Task<IActionResult> Index()
        {
            IEnumerable<Takmicenje> takmicenja = null;

            var request = new HttpRequestMessage(HttpMethod.Get, "takmicenje");
            //request.Headers.Add("Authorization", "Bearer " + HttpContext.User.Claims.SingleOrDefault(c => c.Type == "token").Value);
            var client = _clientFactory.CreateClient("takmicenje");
            var response = await client.SendAsync(request);

            //if (string.IsNullOrEmpty(HttpContext.Session.GetString("token")))
            //{
            //    return RedirectToAction("Login", "Account");
            //}

            if (response.IsSuccessStatusCode)
            {
                var result = await response.Content.ReadAsAsync<IList<Takmicenje>>();
                takmicenja = result;
            }
            else
            {
                takmicenja = Enumerable.Empty<Takmicenje>();
                ModelState.AddModelError(string.Empty, "Greska");
            }

            NovoTakmicenjeSvaTakmicenja viewModel = new NovoTakmicenjeSvaTakmicenja()
            {
                SvaTakmicenja = takmicenja,
            };

            if (TempData["noviGreska"] != null)
            {
                ModelState.AddModelError(string.Empty, TempData["noviGreska"].ToString());
            }

            return View(viewModel);
        }

        //[Breadcrumb("Novo takmicenje", FromAction = "Index", FromController = typeof(TakmicenjeController))]
        //public IActionResult Create()
        //{
        //    return View();
        //}

        [HttpPost]
        public async Task<IActionResult> Create(Takmicenje takmicenje)
        {
            var client = _clientFactory.CreateClient("takmicenje");
            //client.DefaultRequestHeaders.Add("Authorization", "Bearer " + HttpContext.User.Claims.SingleOrDefault(c => c.Type == "token").Value);
            var newFileName = string.Empty;

            if (HttpContext.Request.Form.Files != null)
            {
                var fileName = string.Empty;

                var files = HttpContext.Request.Form.Files;

                foreach (var file in files)
                {
                    if (file.Length > 0)
                    {
                        fileName = ContentDispositionHeaderValue.Parse(file.ContentDisposition).FileName.Trim('"');

                        var myUniqueFileName = Convert.ToString(Guid.NewGuid());

                        var FileExtension = Path.GetExtension(fileName);

                        newFileName = myUniqueFileName + FileExtension;

                        fileName = Path.Combine(_environment.WebRootPath, "images") + $@"\{newFileName}";

                        takmicenje.Slika = "images/" + newFileName;

                        using (FileStream fs = System.IO.File.Create(fileName))
                        {
                            file.CopyTo(fs);
                            fs.Flush();
                        }
                    }
                }
            }
            takmicenje.StatusId = Status.Nastupajuce;
            var post = await client.PostAsJsonAsync<Takmicenje>("takmicenje", takmicenje);

            if (post.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }

            TempData["noviGreska"] = post.Content.ReadAsStringAsync().Result;

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(int id)
        {
            var request = new HttpRequestMessage(HttpMethod.Delete, "takmicenje/" + id);
            var client = _clientFactory.CreateClient("takmicenje");
            await client.SendAsync(request);

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Edit(Takmicenje takmicenje, int id)
        {
            var client = _clientFactory.CreateClient("takmicenje");

            //kod vezan za sliku treba da se prebaci u zasebnu funkciju
            var newFileName = string.Empty;

            if (HttpContext.Request.Form.Files != null)
            {
                var fileName = string.Empty;

                var files = HttpContext.Request.Form.Files;

                foreach (var file in files)
                {
                    if (file.Length > 0)
                    {
                        fileName = ContentDispositionHeaderValue.Parse(file.ContentDisposition).FileName.Trim('"');

                        var myUniqueFileName = Convert.ToString(Guid.NewGuid());
                        var FileExtension = Path.GetExtension(fileName);

                        newFileName = myUniqueFileName + FileExtension;

                        fileName = Path.Combine(_environment.WebRootPath, "images") + $@"\{newFileName}";
                        takmicenje.Slika = "images/" + newFileName;

                        using (FileStream fs = System.IO.File.Create(fileName))
                        {
                            file.CopyTo(fs);
                            fs.Flush();
                        }
                    }
                }
            }

            var response = await client.PutAsJsonAsync("takmicenje/" + id, takmicenje);

            if (!response.IsSuccessStatusCode)
            {
                return StatusCode(500, response.Content.ReadAsStringAsync().Result);
            }

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> TakmicenjeTabelaIndex(int takmicenjeId, string takmicenjeNaziv)
        {
            ViewData["naziv"] = takmicenjeNaziv;
            //IEnumerable<GrupaZadataka> listaGrupaZadataka = null;
            //var client = _clientFactory.CreateClient("takmicenje");
            //var request = new HttpRequestMessage(HttpMethod.Get, "grupaZadataka/" + takmicenjeId);
            //request.Headers.Add("Authorization", "Bearer " + HttpContext.User.Claims.SingleOrDefault(c => c.Type == "token").Value);

            //var response = await client.SendAsync(request);

            //if (response.IsSuccessStatusCode)
            //{
            //    var odg = await response.Content.ReadAsAsync<IList<GrupaZadataka>>();
            //    listaGrupaZadataka = odg;
            //}
            //else
            //{
            //    listaGrupaZadataka = Enumerable.Empty<GrupaZadataka>();
            //}

            //TakmicenjeTabelaViewModel viewModel = new TakmicenjeTabelaViewModel()
            //{
            //    GrupeZadataka = listaGrupaZadataka
            //};

            return View("TakmicenjeTabela");
        }
    }
}

BrainfinityWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BrainfinityWebApp</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/lib/bootstrap-datepicker/dist/css/bootstrap-datepicker3.min.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>

    <div class="wrapper">
        <div class="sidebar" id="sidebar">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-xs-2 col-sm-2 col-lg-2">
                        <a href="#" id="sidebarExpanded"><span><img src="~/images/menu.png" /></span></a>
                    </div>
                    <div class="col-xs-10 col-sm-10 col-lg-10">
                        <img id="logo" src="~/images/Brainfinity_logo_1.png" />
                    </div>
                </div>

                <div class="row profil-slika">
                    <div class="col-lg-2 col-sm-2 col-xs-2"></div>
                    <div class="col-lg-8 col-sm-8 col-xs-8">
                        <img id="avatar" alt="Screenshot_1.png" src="" />
                    </div>
                    <div class="col-lg-2 col-sm-2 col-xs-2"></div>
                </div>

                <div class="row profil-ime">
                    <div class="col-lg-2 col-sm-2 col-xs-2"></div>
                    <div class="col-lg-8 col-sm-8 col-xs-8">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <h3 class="text-center">@User.Claims.SingleOrDefault(c => c.Type == System.Security.Claims.ClaimTypes.Name).Value</h3>
                            <h5 class="text-center">@User.Claims.SingleOrDefault(c => c.Type == System.Security.Claims.ClaimTypes.Role).Value</h5>

                        }
                    </div>
                    <div class="col-lg-2 col-sm-2 col-xs-2"></div>
                </div>
            </div>

            <ul id="meni">
                <li class="item" id="users"><a href="@Url.Action("Index", "Home")"><img src="~/images/users-dark.png" /><span>Korisnici</span></a></li>
                <li class="item" id="award"><a href="@Url.Action("Index","Takmicenje")"><img src="~/images/award-dark.png" /><span>Takmičenja</span></a></li>
                <li class="item" id="bell"><a href="@Url.Action("Index","Home")"><img src="~/images/bell-dark.png" /><span>Korekture</span></a></li>
            </ul>

            @if (User.Identity.IsAuthenticated)
            {

                <div class="logout">
                    <a id="logout" href="@Url.Action("Logout", "Account")"><img src="~/images/log-out.png" /><span style="padding-left:15px; vertical-align: middle;">Odjavi se</span></a>
                </div>

            }
        </div>
        <div id="content">
            <breadcrumb></breadcrumb>
            <div class="container-fluid body-content">
                @RenderBody()
            </div>

            @*<footer>*@
            @*<p>&copy; 2020 - BrainfinityWebApp</p>
                </footer>*@
        </div>
    </div>

    <partial name="_CookieConsentPartial" />

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @if (User.Identity.IsAuthenticated)
    {
        <script>

            if (!sessionStorage.getItem("avatar")) {
                var url = "https://localhost:44376/Account/Korisnik";
                $.get(url, function (data) {
                    console.log("data: " + data);
                    var item = "data:image/png;base64," + data;
                    sessionStorage.setItem("avatar", item);
                    $("#avatar").attr("src", sessionStorage.getItem("avatar"));

                });

            }
            $("#avatar").attr("src", sessionStorage.getItem("avatar"));
            console.log("ss:" + sessionStorage.getItem("avatar"));
        </script>

    }

    @RenderSection("Scripts", required: false)
</body>
</html>