BrainfinityWebApp/Models/Zadatak.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BrainfinityWebApp.Models
{
    public class Zadatak
    {
        public int Id { get; set; }

        [Display(Name = "Ime zadatka")]
        public string ZadatakNaziv { get; set; }

        public int Bodovi { get; set; }
        public GrupaZadataka GrupaZadataka { get; set; }
        public int GrupaZadatakaId { get; set; }
    }
}

BrainfinityWebApp/Controllers/ZadatakController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using BrainfinityWebApp.Models;
using BrainfinityWebApp.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BrainfinityWebApp.Controllers
{
    [Authorize(Roles = "Supervizor")]
    public class ZadatakController : Controller
    {
        private readonly IHttpClientFactory _client;

        public ZadatakController(IHttpClientFactory client)
        {
            _client = client;
        }

        public async Task<IActionResult> CreateZadatak(Zadatak zadatak, int takmicenjeId)
        {
            var client = _client.CreateClient("takmicenje");
            var request = await client.PostAsJsonAsync<Zadatak>("zadatak", zadatak);

            return RedirectToAction("Index", "GrupaZadataka", new { takmicenjeId });
        }

        public async Task<IActionResult> DeleteZadatak(int zadatakId, int takmicenjeId)
        {
            var client = _client.CreateClient("takmicenje");
            var request = await client.DeleteAsync("zadatak/" + zadatakId);

            return RedirectToAction("Index", "GrupaZadataka", new { takmicenjeId });
        }

        public async Task<IActionResult> EditZadatak(Zadatak zadatak, int takmicenjeId, int zadatakId)
        {
            var client = _client.CreateClient("takmicenje");
            var request = await client.PutAsJsonAsync<Zadatak>("zadatak/" + zadatakId, zadatak);

            return RedirectToAction("Index", "GrupaZadataka", new { takmicenjeId });
        }
    }
}

BrainfinityWebApp/Views/GrupaZadataka/Components/Zadatak/IndexPartial.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@model BrainfinityWebApp.ViewModels.ZadatakIndexViewModel
@foreach (var zadatak in Model.SviZadaci)
{
    var deleteZadatak = "deleteZadatak" + zadatak.Id;
    var editZadatak = "editZadatak" + zadatak.Id;
    <div class="div-zadatak">
        <div class="grupa-zadataka-zadatak">
            <div class="row">
                <div class="col-md-9">
                    <h5 class="zadatak-naslov">@zadatak.ZadatakNaziv</h5>
                </div>
                <div class="col-md-3">
                    <div style="padding-right: 15px;">
                        <a href="#" class="pull-right" data-toggle="modal" data-target="#@editZadatak">
                            <img src="~/images/edit.png" style="height:14px; width: 14px" />
                        </a>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3 col-md-offset-9">
                    <div style="padding-right: 15px;">
                        <a href="#" class="pull-right" data-toggle="modal" data-target="#@deleteZadatak">
                            <img src="~/images/trash.png" style="height:14px; width: 14px" />
                        </a>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="col-md-2" style="padding-right:5px;">
                        <div class="pull-right tacka"></div>
                    </div>
                    <div class="col-md-3" style="padding:0;">
                        <img src="~/images/users-dark.png" class="pull-left" style="height:18px; width:21px;" />
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="col-md-2" style="padding-right:5px;">
                        <div class="pull-right tacka"></div>
                    </div>
                    <div class="col-md-3" style="padding:0;">
                        <img src="~/images/pregledac-dark.png" class="pull-left" style="margin-top:5px;" />
                    </div>
                </div>
            </div>
        </div>
    </div>
}
@if (Model.SviZadaci.Count() < 5)
{
    var grupaId = "zadatakGrupa" + Model.GrupaId;

    <a href="#" id="@Model.GrupaId" data-toggle="modal" data-target="#@grupaId">

        <div class="div-zadatak">
            <div class="grupa-zadataka-novi-zadatak">
                <div class="row">
                    <div class="col-md-9">
                        <h5 class="zadatak-naslov">Novi zadatak</h5>
                    </div>
                    <div class="col-md-2">
                        <img src="~/images/x-circle.png" class="pull-right" />
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        &nbsp;
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <div class="col-md-2" style="padding-right:5px;">
                            <div class="pull-right tacka"></div>
                        </div>
                        <div class="col-md-3" style="padding:0;">
                            <img src="~/images/users.png" class="pull-left" />
                        </div>
                    </div>

                    <div class="col-md-4">
                        <div class="col-md-2" style="padding-right:5px;">
                            <div class="pull-right tacka"></div>
                        </div>
                        <div class="col-md-3" style="padding:0;">
                            <img src="~/images/pregledac.png" class="pull-left" style="margin-top:5px;" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </a>

}

@foreach (var zadatak in Model.SviZadaci)
{
    var deleteZadatak = "deleteZadatak" + zadatak.Id;

    <div class="modal fade" id="@deleteZadatak" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <div class="row">
                        @*<div class="col-md-1"></div>*@
                        <div class="col-md-10 col-lg-offset-1">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="font-size:40px;"><span aria-hidden="true">&times;</span></button>

                            <h4 class="modal-title" id="myModalLabel">Brisanje zadatka</h4>
                        </div>
                    </div>
                </div>
                @using (Html.BeginForm("DeleteZadatak", "Zadatak"))
                {
                    <div class="modal-body">
                        <div class="col-md-10 col-md-offset-1">
                            Da li ste sigurni da želite da obrišete zadatak
                            <br />
                            "<b><u style="text-decoration-color:red;">@zadatak.ZadatakNaziv</u></b>"
                        </div>
                        <br />
                        <br />
                    </div>
                    <div class="modal-footer">
                        <div class="row">
                            <div class="col-md-10 col-lg-offset-1">
                                @Html.Hidden("zadatakId", zadatak.Id)
                                @Html.Hidden("takmicenjeId", ViewData["TakmicenjeId"])
                                <button type="button" class="btn btn-default" data-dismiss="modal">Odustani</button>
                                <button type="submit" class="btn btn-danger">
                                    <span>
                                        <img src="~/images/trash-light.png" style="height:16px; width: 16px;" />&nbsp; Obriši
                                    </span>
                                </button>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>

    var editZadatak = "editZadatak" + zadatak.Id;
    <div class="modal fade" id="@editZadatak" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <div class="row">
                        @*<div class="col-md-1"></div>*@
                        <div class="col-md-10 col-lg-offset-1">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="font-size:40px;"><span aria-hidden="true">&times;</span></button>

                            <h4 class="modal-title" id="myModalLabel">Izmeni zadatak</h4>
                        </div>
                    </div>
                </div>
                @using (Html.BeginForm("EditZadatak", "Zadatak"))
                {
                    <div class="modal-body">
                        <div class="col-md-10 col-md-offset-1">
                            @Html.LabelFor(m => zadatak.ZadatakNaziv)
                            @Html.TextBoxFor(m => zadatak.ZadatakNaziv, new { @class = "form-control" })
                        </div>
                        <br />
                        <div class="col-md-3 col-md-offset-1">
                            @Html.LabelFor(m => zadatak.Bodovi)
                            @Html.EditorFor(m => zadatak.Bodovi, new { @class = "form-control" })
                        </div>
                        <br />
                    </div>
                    <div class="modal-footer">
                        <div class="row">
                            <div class="col-md-10 col-lg-offset-1">
                                @Html.Hidden("zadatak.GrupaZadatakaId", zadatak.GrupaZadatakaId)
                                @Html.Hidden("takmicenjeId", ViewData["TakmicenjeId"])
                                @Html.Hidden("zadatakId", zadatak.Id)
                                <button type="button" class="btn btn-default" data-dismiss="modal">Odustani</button>
                                <button type="submit" class="btn btn-primary">
                                    <span>
                                        <img src="~/images/layers.png" style="height:16px; width: 16px;" />&nbsp; Potvrdi
                                    </span>
                                </button>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
}

@section Scripts{
    <script>
        $("#modaldugme").on("click", function (e) {
            e.preventdefault();

        });
    </script>
}